*** Settings ***
Resource    ../resources/api_marvel.resource


*** Test Cases ***

ENDPOINT CHARACTERS - SUCESSO
    DADO QUE EU CONSULTE O ENDPOINT 
	# QUANDO EU PASSAR OS PARAMETROS 
	ENTÃO A API DEVE RETORNAR 200 SUCESSO     200

ENDPOINT CHARACTERS - APIKEY INVALIDA
    DADO QUE EU CONSULTE O ENDPOINT COM APIKEY INVALIDA
	# QUANDO EU PASSAR OS PARAMETROS 
	ENTÃO A API DEVE RETORNAR 200 SUCESSO     401