*** Settings ***
Resource    ../resources/api_marvel.resource


*** Test Cases ***

ENDPOINT CHARACTERS - SUCESSO
    DADO QUE EU CONSULTE O ENDPOINT 
	QUANDO EU PASSAR OS PARAMETROS 
	ENTÃO A API DEVE RETORNAR    200

ENDPOINT CHARACTERS - APIKEY INVALIDA
    DADO QUE EU CONSULTE O ENDPOINT 
	QUANDO EU PASSAR OS PARAMETROS INVALIDOS
	ENTÃO A API DEVE RETORNAR     401  

CONSULTAR API CHARACTERS SEM USER KEY  
    DADO QUE EU CONSULTE O ENDPOINT 
    QUANDO EU PASSAR PARAMETROS SEM USER KEY 
    ENTÃO A API DEVE RETORNAR     409  

CONSULTAR API CHARACTERS COM HASH - VALIDO
    DADO QUE EU CONSULTE O ENDPOINT 
    QUANDO EU PASSAR PARAMETROS COM HASH VALIDO
     ENTÃO A API DEVE RETORNAR     200  


CONSULTAR API CHARACTERS COM HASH - INVALIDO
    DADO QUE EU CONSULTE O ENDPOINT 
    QUANDO EU PASSAR PARAMETROS COM HASH INVALIDO
    ENTÃO A API DEVE RETORNAR     401  

CONSULTAR API CHARACTERS SEM O HASH
    DADO QUE EU CONSULTE O ENDPOINT 
    QUANDO EU PASSAR PARAMETROS SEM O HASH
    ENTÃO A API DEVE RETORNAR     409  

      



