*** Settings ***
Resource    ../resources/api_reqres.resource




*** Test Cases ***
CONSULTAR USUARIOS COM SUCESSO
	DADO QUE CONSULTE O ENDPOINT /api/users 
	QUANDO EU PASSAR O PARAMETRO PAGE=1 
	ENTÃO A API DEVE RETORNAR     200
	ENTÃO VALIDO O CONTEUDO DO RESPONSE BODY

CONSULTAR USUARIOS COM SUCESSO SEM PAGINAÇÃO
	DADO QUE CONSULTE O ENDPOINT /api/users 
	QUANDO EU NÃO PASSAR O PARAMETRO PAGE
	ENTÃO A API DEVE RETORNAR     200

CONSULTAR USUARIOS COM SUCESSO COM PAGINAÇÃO SEM DATA
	DADO QUE CONSULTE O ENDPOINT /api/users 
	QUANDO EU NÃO PASSAR O PARAMETRO PAGE=3
	ENTÃO A API DEVE RETORNAR     200


###################################################################################

CONSULTAR USUARIOS COM SUCESSO COM PARAMETRO
	DADO QUE CONSULTE UM SINGLE USER NO ENDPOINT /api/users
	QUANDO EU PASSAR O PARAMETRO ID=2
	ENTÃO A API DEVE RETORNAR  200  


CONSULTAR USUARIOS COM SUCESSO SEM ID
	DADO QUE CONSULTE UM SINGLE USER NO ENDPOINT /api/users
	QUANDO EU NÃO PASSAR O PARAMETRO ID
	ENTÃO A API DEVE RETORNAR  200

QUANDO EU CONSULTAR USUARIOS COM ID INVALIDO
	DADO QUE CONSULTE UM SINGLE USER NO ENDPOINT /api/users
	QUANDO EU PASSAR O PARAMETRO COM ID INVALIDO
	ENTÃO A API DEVE RETORNAR   404


CONSULTAR USUARIOS COM ENDPOINT DESCONHECIDO SEM O PARAMETRO
    DADO QUE EU CONSULTE O ENDPOINT DESCONHECIDO
	QUANDO EU PASSAR SEM PARAMETRO 
	ENTÃO A API DEVE RETORNAR 	200
	ENTÃO VALIDO O CONTEUDO DO RESPONSE BODY DESCONHECIDO LISTA
    


CONSULTAR USUARIOS COM ENDPOINT DESCONHECIDO COM PARAMETRO VALIDO
	DADO QUE EU CONSULTE O ENDPOINT DESCONHECIDO
	QUANDO EU PASSAR UM PARAMETRO VALIDO 
	ENTÃO A API DEVE RETORNAR 	200
	ENTÃO VALIDO O CONTEUDO DO RESPONSE BODY DESCONHECIDO
	

CONSULTAR USUARIOS COM ENDPOINT DESCONHECIDO COM PARAMETRO INVALIDO
	DADO QUE EU CONSULTE O ENDPOINT DESCONHECIDO
	QUANDO EU PASSAR UM PARAMETRO INVALIDO 
	ENTÃO A API DEVE RETORNAR  404

################################################################################################################

CRIAR USUARIO ENDPOINT API/USERS                                                                
	DADO QUE EU TENHA NOME E JOB DO USUARIO
	QUANDO EU EFETUAR A REQUISIÇÃO 
	ENTÃO A API DEVE RETORNAR   201


CRIAR USUARIO ENDPOINT API/USERS SEM O JOB                                                                  
	DADO QUE EU TENHA NOME E JOB DO USUARIO 
	QUANDO EU EFETUAR A REQUISIÇÃO SEM O JOB
	ENTÃO A API DEVE RETORNAR  400
 


CRIAR USUARIO ENDPOINT API/USERS SEM O NOME DO USUARIO                                                                   
	DADO QUE EU TENHA NOME E JOB DO USUARIO 
	QUANDO EU EFETUAR A REQUISIÇÃO SEM O NOME DO USUARIO
	ENTÃO A API DEVE RETORNAR  400



CRIAR USUARIO ENDPOINT API/USERS COM NOME DO USUARIO DIFERENTE                                                                    
	DADO QUE EU TENHA NOME E JOB DO USUARIO 
	QUANDO EU EFETUAR A REQUISIÇÃO COM NOME DIFERENTE
	ENTÃO A API DEVE RETORNAR  201
 
 #####################################################################################

 
ATUALIZAR USUARIO NO ENDPOINT /API/USERS - NOME INVALIDO
	QUANDO QUE EU ATUALIZAR UM USUARIO 
	QUANDO EU ATUALIZAR O MOME DO USUARIO PARA NUMEROS
	ENTÃO A API DEVE RETORNAR  400



ATUALIZAR USUARIO NO ENDPOINT /API/USERS - SEM JOB
	QUANDO QUE EU ATUALIZAR UM USUARIO 
	QUANDO EU ATUALIZAR USUARIO SEM O JOB
	ENTÃO A API DEVE RETORNAR  400


ATUALIZAR USUARIO NO ENDPOINT /API/USERS - SEM NOME
	QUANDO QUE EU ATUALIZAR UM USUARIO  
	QUANDO EU ATUALIZAR USUARIO SEM NOME
	ENTÃO A API DEVE RETORNAR  400

####################################################################

DELETAR USUARIO NO ENDPOINT /API/USERS/2
	DADO QUE EU CONSULTE O ENDPOINT 
   	QUANDO EU DELETAR UM USUARIO
	ENTÃO A API DEVE RETORNAR    204
    

