*** Settings ***
Resource    ../resources/api_reqres.resource

Library    RequestsLibrary


*** Test Cases ***
CONSULTAR USUARIOS COM SUCESSO
	DADO QUE CONSULTE O ENDPOINT /api/users 
	QUANDO EU PASSAR O PARAMETRO PAGE=1 
	ENTÃO A API DEVE RETORNAR     200
	ENTÃO VALIDO O CONTEUDO DO RESPONSE BODY

CONSULTAR USUARIOS COM SUCESSO SEM PAGINAÇÃO
	DADO QUE CONSULTE O ENDPOINT /api/users 
	QUANDO EU NÃO PASSAR O PARAMETRO PAGE
	ENTÃO A API DEVE RETORNAR     200

CONSULTAR USUARIOS COM SUCESSO COM PAGINAÇÃO SEM DATA
	DADO QUE CONSULTE O ENDPOINT /api/users 
	QUANDO EU NÃO PASSAR O PARAMETRO PAGE=3
	ENTÃO A API DEVE RETORNAR     200


###################################################################################

CONSULTAR USUARIOS COM SUCESSO
	DADO QUE CONSULTE UM SINGLE USER NO ENDPOINT /api/users
	QUANDO EU PASSAR O PARAMETRO ID=2
	ENTÃO A API DEVE RETORNAR  200  


CONSULTAR USUARIOS COM SUCESSO SEM ID
	DADO QUE CONSULTE UM SINGLE USER NO ENDPOINT /api/users
	QUANDO EU NÃO PASSAR O PARAMETRO ID
	ENTÃO A API DEVE RETORNAR  200

QUANDO EU CONSULTAR USUARIOS COM ID INVALIDO
	DADO QUE CONSULTE UM SINGLE USER NO ENDPOINT /api/users
	QUANDO EU PASSAR O PARAMETRO COM ID INVALIDO
	ENTÃO A API DEVE RETORNAR   404


CONSULTAR USUARIOS COM ENDPOINT DESCONHECIDO SEM O PARAMETRO
    DADO QUE EU CONSULTE O ENDPOINT DESCONHECIDO
	QUANDO EU PASSAR SEM PARAMETRO 
	ENTÃO A API DEVE RETORNAR 	200
	ENTÃO VALIDO O CONTEUDO DO RESPONSE BODY DESCONHECIDO LISTA
    


CONSULTAR USUARIOS COM ENDPOINT DESCONHECIDO COM PARAMETRO VALIDO
	DADO QUE EU CONSULTE O ENDPOINT DESCONHECIDO
	QUANDO EU PASSAR UM PARAMETRO VALIDO 
	ENTÃO A API DEVE RETORNAR 	200
	ENTÃO VALIDO O CONTEUDO DO RESPONSE BODY DESCONHECIDO
	

CONSULTAR USUARIOS COM ENDPOINT DESCONHECIDO COM PARAMETRO INVALIDO
	DADO QUE EU CONSULTE O ENDPOINT DESCONHECIDO
	QUANDO EU PASSAR UM PARAMETRO INVALIDO 
	ENTÃO A API DEVE RETORNAR  404


